### PR TITLE
Fix #368

### LINKED ISSUE #368: Incorrect depth from ivar variants reported in variants long table
### Description of the bug

When read depth is very high, `ivar variants` outputs depth in scientific notation. `variants_long_table` reports only the part of the number before the decimal, resulting in inaccurate depths and allele frequencies.

I believe the issue can be resolved by modifying https://github.com/nf-core/viralrecon/blob/master/bin/ivar_variants_to_vcf.py#L123 to `INFO = f"DP={int(float(line[11]))}"` to always report depth in vcf as an integer.

`$ grep 'e+' out/variants/ivar/ww.tsv`
| REGION | POS | REF | ALT | REF_DP | REF_RV | REF_QUAL | ALT_DP | ALT_RV | ALT_QUAL | ALT_FREQ | TOTAL_DP | PVAL | PASS | GFF_FEATURE | REF_CODON | REF_AA | ALT_CODON | ALT_AA |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
| MN908947.3 | 21730 | A | G | 1317930 | 667938 | 35 | 14947 | 7521 | 36 | 0.0112138 | 1.33291e+06 | 0 | TRUE | cds-QHD43416.1 | TTA | L | TTG | L |
| MN908947.3 | 22583 | G | +T | 1474471 | 730754 | 36 | 79562 | 0 | 20 | 0.0531601 | 1.49665e+06 | 0 | TRUE | NA | NA | NA | NA | NA |
| MN908947.3 | 22977 | T | C | 1910409 | 57949 | 36 | 87378 | 1674 | 36 | 0.0437341 | 1.99794e+06 | 0 | TRUE | cds-QHD43416.1 | ATC | I | ACC | T |
| MN908947.3 | 23052 | T | A | 1983145 | 60241 | 36 | 12052 | 145 | 36 | 0.0060397 | 1.99546e+06 | 0 | TRUE | cds-QHD43416.1 | TTC | F | TAC | Y |
| MN908947.3 | 23126 | G | A | 3716960 | 1840637 | 37 | 5148 | 2450 | 36 | 0.00138304 | 3.72223e+06 | 1.39735e-52 | TRUE | cds-QHD43416.1 | GCA | A | ACA | T |
| MN908947.3 | 23256 | T | C | 2436217 | 1880072 | 36 | 4472 | 348 | 36 | 0.00183214 | 2.44086e+06 | 8.3265e-135 | TRUE | cds-QHD43416.1 | TTT | F | TCT | S |
| MN908947.3 | 24223 | C | +T | 1600383 | 258881 | 36 | 9068 | 0 | 20 | 0.00566151 | 1.60169e+06 | 1 | FALSE | NA | NA | NA | NA | NA |
| MN908947.3 | 24419 | A | G | 2602143 | 1303101 | 37 | 3394 | 1760 | 35 | 0.00130258 | 2.6056e+06 | 9.93939e-25 | TRUE | cds-QHD43416.1 | AAC | N | GAC | D |
| MN908947.3 | 24442 | C | A | 1274046 | 1271015 | 36 | 36373 | 36310 | 36 | 0.0277556 | 1.31047e+06 | 0 | TRUE | cds-QHD43416.1 | AAC | N | AAA | K |
| MN908947.3 | 24516 | A | G | 3613820 | 1381048 | 37 | 3692 | 218 | 36 | 0.00102047 | 3.61794e+06 | 0.192741 | FALSE | cds-QHD43416.1 | GAC | D | GGC | G |

`$ awk -F, '$10>1' out/variants/ivar/variants_long_table.csv`
| SAMPLE | CHROM | POS | REF | ALT | FILTER | DP | REF_DP | ALT_DP | AF | GENE | EFFECT | HGVS_C | HGVS_P | HGVS_P_1LETTER | CALLER |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
| ww | MN908947.3 | 21730 | A | G | PASS | 1 | 1317930 | 14947 | 14947.0 | S | synonymous_variant | c.168A>G | p.Leu56Leu | p.L56L | ivar |
| ww | MN908947.3 | 22583 | G | GT | PASS | 1 | 1474471 | 79562 | 79562.0 | S | frameshift_variant&stop_gained | c.1026dupT | p.Asn343fs | p.N343fs | ivar |
| ww | MN908947.3 | 22977 | T | C | PASS | 1 | 1910409 | 87378 | 87378.0 | S | missense_variant | c.1415T>C | p.Ile472Thr | p.I472T | ivar |
| ww | MN908947.3 | 23052 | T | A | PASS | 1 | 1983145 | 12052 | 12052.0 | S | missense_variant | c.1490T>A | p.Phe497Tyr | p.F497Y | ivar |
| ww | MN908947.3 | 23126 | G | A | PASS | 3 | 3716960 | 5148 | 1716.0 | S | missense_variant | c.1564G>A | p.Ala522Thr | p.A522T | ivar |
| ww | MN908947.3 | 23256 | T | C | PASS | 2 | 2436217 | 4472 | 2236.0 | S | missense_variant | c.1694T>C | p.Phe565Ser | p.F565S | ivar |
| ww | MN908947.3 | 24223 | C | CT | ft | 1 | 1600383 | 9068 | 9068.0 | S | frameshift_variant | c.2664dupT | p.Gly889fs | p.G889fs | ivar |
| ww | MN908947.3 | 24419 | A | G | PASS | 2 | 2602143 | 3394 | 1697.0 | S | missense_variant | c.2857A>G | p.Asn953Asp | p.N953D | ivar |
| ww | MN908947.3 | 24442 | C | A | PASS | 1 | 1274046 | 36373 | 36373.0 | S | missense_variant | c.2880C>A | p.Asn960Lys | p.N960K | ivar |
| ww | MN908947.3 | 24516 | A | G | ft | 3 | 3613820 | 3692 | 1230.67 | S | missense_variant | c.2954A>G | p.Asp985Gly | p.D985G | ivar |

### Command used and terminal output

_No response_

### Relevant files

_No response_

### System information

Nextflow version: 19.01.0.5050
Hardware: Cloud VM
Executor: local
Container engine: Docker
OS: Linux
Version of nf-core/viralrecon: 2.5

### PR DESCRIPTION
**Pull request by drpatelh**
Closes #368

### CODE REVIEW

**Review by maxulysse — APPROVED** [review]

File: lib/NfcoreTemplate.groovy [hunk 1]
```diff
@@ -32,6 +32,18 @@ class NfcoreTemplate {
...
 
+    //
+    //  Warn if using custom configs to provide pipeline parameters
+    //
+    public static void warnParamsProvidedInConfig(workflow, log) {
+        if (workflow.configFiles.size() > 1) {
+            log.warn "[$workflow.manifest.name] Multiple config files detected!\n" +
+                    "Parameters passed via custom config files including the '-c' Nextflow option will be ignored.\n" +
+                    "Please provide pipeline parameters via the '-params-file' Nextflow option instead.\n" +
+                    "Docs: https://nf-co.re/usage/configuration?q=params#custom-configuration-files\n"
```
Comment (ewels) [inline lib/NfcoreTemplate.groovy]:
```suggestion
                    "Docs: https://nf-co.re/usage/configuration#custom-configuration-files\n"
```

File: README.md [hunk 2]
```diff
@@ -98,6 +98,8 @@ A number of improvements were made to the pipeline recently, mainly with regard
 
 4. Start running your own analysis!
 
+   > - Parameters passed via custom config files including the `-c` Nextflow option will be ignored. Please provide pipeline parameters via the `-params-file` Nextflow option instead; see [docs](https://nf-co.re/usage/configuration?q=params#custom-configuration-files).
```
Comment (ewels) [inline README.md]:
```suggestion
   > - Parameters passed via custom config files including the `-c` Nextflow option will be ignored. Please provide pipeline parameters via the `-params-file` Nextflow option instead; see [docs](https://nf-co.re/usage/configuration#custom-configuration-files).
```

File: docs/usage.md [hunk 3]
```diff
@@ -4,6 +4,10 @@
 
 > _Documentation of pipeline parameters is generated automatically from the pipeline schema and can no longer be found in markdown files._
 
+## Pipeline parameters
+
+Parameters passed via custom config files including the `-c` Nextflow option will be ignored. Please provide pipeline parameters via the `-params-file` Nextflow option instead; see [docs](https://nf-co.re/usage/configuration?q=params#custom-configuration-files).
```
Comment (ewels) [inline docs/usage.md]:
```suggestion
Parameters passed via custom config files including the `-c` Nextflow option will be ignored. Please provide pipeline parameters via the `-params-file` Nextflow option instead; see [docs](https://nf-co.re/usage/configuration#custom-configuration-files).
```

**Review by ewels — APPROVED** [review]
Don't think you need the `q=params` in the URL. I guess it's left over from a website search and don't think it's doing anything.

**Comment by wutron** [comment]
Unrelated to the fix, but I think there is an issue in the subworkflows as well, e.g. remove `/main`.
https://github.com/drpatelh/nf-core-viralrecon/blob/fixes/workflows/illumina.nf#L99

**Comment by drpatelh** [comment]
Sorry, decided to push some other changes here @wutron because it was quicker

> Unrelated to the fix, but I think there is an issue in the subworkflows as well, e.g. remove /main.
https://github.com/drpatelh/nf-core-viralrecon/blob/fixes/workflows/illumina.nf#L99

This should be fine with or without the `main`? The former was the previous convention.

File: lib/NfcoreTemplate.groovy [hunk 4]
```diff
@@ -32,6 +32,21 @@ class NfcoreTemplate {
...
+    //  Warn if using custom configs to provide pipeline parameters
+    //
+    public static void warnParamsProvidedInConfig(workflow, log) {
+        if (workflow.configFiles.size() > 1) {
+            log.warn "=============================================================================\n" +
+                "  Multiple config files detected!\n" +
+                "  Please provide pipeline parameters via the CLI or Nextflow '-params-file' option.\n" +
+                "  Custom config files including those provided by the '-c' Nextflow option can be\n" +
+                "  used to provide any configuration except for parameters.\n\n" +
+                "  Docs: https://nf-co.re/usage/configuration#custom-configuration-files\n" +
```
Comment (ewels) [inline lib/NfcoreTemplate.groovy:45]: Bit late so not my best, but wonder if this is _slightly_ clearer? Gives some reasoning..

```suggestion
                "  Multiple config files detected!\n" +
                "  Please provide pipeline parameters via the CLI or Nextflow '-params-file' option.\n" +
                "  Nextflow config files (eg. using '-c') do not overwrite params properly, but can\n" +
                "  be used for other config scopes.\n\n" +
                "  Docs: https://nf-co.re/usage/configuration#custom-configuration-files\n" +
```

**Comment by wutron** [comment]
> Sorry, decided to push some other changes here @wutron because it was quicker
> 
> > Unrelated to the fix, but I think there is an issue in the subworkflows as well, e.g. remove /main.
> > https://github.com/drpatelh/nf-core-viralrecon/blob/fixes/workflows/illumina.nf#L99
> 
> This should be fine with or without the `main`? The former was the previous convention.

Should https://github.com/drpatelh/nf-core-viralrecon/blob/fixes/workflows/illumina.nf#L99 have `/main` then?

**Comment by wutron** [comment]
> Closes #368

Confirm fixed.  Sorry for delay.  Had to re-process several million reads.

**Comment by drpatelh** [comment]
> Should https://github.com/drpatelh/nf-core-viralrecon/blob/fixes/workflows/illumina.nf#L99 have /main then?

It doesn't matter whether it does or not. Nextflow will pick up the `main,nf` script by default. I guess we should be consistent with the convention we use though 👍🏽

**Comment by drpatelh** [comment]
> Should https://github.com/drpatelh/nf-core-viralrecon/blob/fixes/workflows/illumina.nf#L99 have /main then?

Fixed https://github.com/nf-core/viralrecon/pull/370/commits/e765818a26471d720976cb197e582fb004d5dd1f

File: lib/NfcoreTemplate.groovy [hunk 5]
```diff
@@ -32,6 +32,21 @@ class NfcoreTemplate {
         }
     }
 
+    //
+    //  Warn if using custom configs to provide pipeline parameters
+    //
+    public static void warnParamsProvidedInConfig(workflow, log) {
+        if (workflow.configFiles.size() > 1) {
+            log.warn "=============================================================================\n" +
```
Comment (jfy133) [inline lib/NfcoreTemplate.groovy]: NO `====`! You will mess with git merge conflicts!!!!!!! :grimacing: :grimacing: :grimacing: :grimacing: :grimacing: :grimacing:

File: lib/NfcoreTemplate.groovy [hunk 6]
```diff
@@ -32,6 +32,21 @@ class NfcoreTemplate {
...
+                "  Multiple config files detected!\n" +
+                "  Please provide pipeline parameters via the CLI or Nextflow '-params-file' option.\n" +
+                "  Custom config files including those provided by the '-c' Nextflow option can be\n" +
+                "  used to provide any configuration except for parameters.\n\n" +
+                "  Docs: https://nf-co.re/usage/configuration#custom-configuration-files\n" +
+                "==================================================================================="
```
Comment (jfy133) [inline lib/NfcoreTemplate.groovy]:
```suggestion
            log.warn "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n" +
                "  Multiple config files detected!\n" +
                "  Please provide pipeline parameters via the CLI or Nextflow '-params-file' option.\n" +
                "  Custom config files including those provided by the '-c' Nextflow option can be\n" +
                "  used to provide any configuration except for parameters.\n\n" +
                "  Docs: https://nf-co.re/usage/configuration#custom-configuration-files\n" +
                "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
```

File: lib/NfcoreTemplate.groovy (hunk 5 above)
Comment (drpatelh) [reply lib/NfcoreTemplate.groovy]: Ohhhh... I hav these all over rnaseq...which symbols work best here?

File: README.md [hunk 7]
```diff
@@ -98,6 +98,8 @@ A number of improvements were made to the pipeline recently, mainly with regard
 
 4. Start running your own analysis!
 
+   > - Please provide pipeline parameters via the CLI or Nextflow `-params-file` option. Custom config files including those provided by the `-c` Nextflow option can be used to provide any configuration except for parameters; see [docs](https://nf-co.re/usage/configuration#custom-configuration-files).
```
Comment (jfy133) [inline README.md:101]: I would not add this here, if you would be new to the pipeline you wouldn't really know passing parameters to pipelines via `-c` exists. You should point instead to the website IF you want to include something: https://nf-co.re/docs/usage/configuration#custom-configuration-files

If you've used the pipeline before, you should know to look at the website therefore you wouldn't be looking at the README as a quick reference

You're risking adding more and more fluff to what is to be very basic intro docs which @grst just tried to remove ;)

Comment (drpatelh) [reply README.md:101]: Whatever is written in the pipeline README is rendered on the website?

I agree with trimming down the boilerplate but this is quite important. A number of users have been stung by it and complained that there is no clear documentation for this in the pipeline. Think we should have it on the website in more detail as well as the pipeline in as many prominent locations as possible. Not sure we should compromise on this if it saves a user countless hours figuring out why their parameters are not being passed to the pipeline.

Comment (drpatelh) [reply README.md:101]: See https://github.com/nf-core/rnaseq/issues/894 for context

Another user spoke to me about this at the Festival of Genomics.

Comment (jfy133) [reply README.md:101]: Ok fair enough. Can you please copy this over to the template though ;-*

Comment (drpatelh) [reply README.md:101]: I'm scrambling to get 2 pipelines out this week and have a bunch of other stuff I need to do before the Hackathon. At the very least I will create an issue pointing to the commits so it can be easily added during the Hackathon.

Once we have revised the website docs we can always trim down the text but let's keep it as it is for now.

Comment (grst) [reply README.md:101]: I think it would also be possible to add a check for this, see 
https://github.com/nf-core/tools/issues/2184
