### PR TITLE
Fix outstanding issues

### LINKED ISSUE #175: MultiQC report does not include all the metrics
When running the dev nf-core/viralrecon v1.2.0dev (224865c), I noticed the multiQC report does not have information for Kraken2 % non-host reads even though the kraken2 reports are generated correctly.  There are NAs instead of actual percentages.  Also the coverage information is not displayed in the variant calling metrics section.
Thanks

Ryan

### PR DESCRIPTION
**Pull request by drpatelh**
Closes #175

### CODE REVIEW

File: bin/plot_mosdepth_regions.r [hunk 1]
```diff
@@ -106,7 +110,7 @@ for (sample in unique(dat$sample)) {
                 ggtitle(paste(sample,'median coverage per amplicon'))
 
           outfile <- paste(OUTDIR,sample,".",OUTSUFFIX,".coverage.pdf", sep='')
-          ggsave(file=outfile, plot, height=3+(0.3*length(unique(sample_dat$region))), width=16, units="cm")
+          ggsave(file=outfile, plot, height=3+(0.2*length(unique(sample_dat$region))), width=16, units="cm", limitsize=FALSE)
```
Comment (JoseEspinosa) [inline bin/plot_mosdepth_regions.r:113]: Was not aware of this option, nice!

**Review by JoseEspinosa — APPROVED** [review]
LGTM

**Review by heuermh — APPROVED** [review]

**Comment by drpatelh** [comment]
Thanks guys!
